apiVersion: apps/v1
kind: Deployment

metadata:
  name: train-ticket-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: train-ticket

  template:
    metadata:
      labels:
        app: train-ticket

    spec:
      containers:
        - name: train-ticket-container
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
