apiVersion: v1
kind: Service

metadata:
  name: train-ticket-service

spec:
  type: NodePort

  selector:
    app: train-ticket

  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
