name: DevSecOps Pipeline

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Maven Build
      run: mvn clean package -DskipTests

    - name: SonarQube Scan
      run: |
        mvn sonar:sonar \
        -Dsonar.projectKey=train-ticket \
        -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Trivy FS Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scan-ref: .

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker Image
      run: |
        IMAGE_TAG=$(date +%s)
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        docker build -t train-ticket:$IMAGE_TAG .

    - name: Tag Image
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        docker tag train-ticket:$IMAGE_TAG \
        $ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/train-ticket:$IMAGE_TAG

    - name: Push Image
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        docker push \
        $ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/train-ticket:$IMAGE_TAG

    - name: Install kubectl
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/stable.txt
        curl -LO https://storage.googleapis.com/kubernetes-release/release/$(cat stable.txt)/bin/linux/amd64/kubectl
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
        --name ${{ secrets.EKS_CLUSTER_NAME }} \
        --region ${{ secrets.AWS_REGION }}

    - name: Deploy Kubernetes
      run: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/deployment.yaml -n train-ticket
        kubectl apply -f k8s/service.yaml
